### PR TITLE
Rounding to Significant Figures

### PR DESCRIPTION
**Pull request by gaborcsardi**
This is from #15.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
@billdenney What is the problem with `signif()`? 

```r
❯ signif(1:10/3, 2)
 [1] 0.33 0.67 1.00 1.30 1.70 2.00 2.30 2.70 3.00 3.30

❯ pretty_signif(1:10/3, 2)
 [1] "0.33" "0.67" "1.0"  "1.3"  "1.7"  "2.0"  "2.3"  "2.7"  "3.0"  "3.3"
```

The `signif()` behavior looks good to me.

**Comment by billdenney** [comment]
The issue is with the character representation:

``` r
as.character(signif(1:10/3, 2))
#>  [1] "0.33" "0.67" "1"    "1.3"  "1.7"  "2"    "2.3"  "2.7"  "3"    "3.3"
```

<sup>Created on 2019-12-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note that the value that should be "1.0", "2.0", and "3.0" for 2 significant figures only have 1 significant figure.

**Comment by gaborcsardi** [comment]
Yeah, but with `format()` it is good:

```r
❯ format(signif(1:10/3, 2))
 [1] "0.33" "0.67" "1.00" "1.30" "1.70" "2.00" "2.30" "2.70" "3.00" "3.30"
```

**Comment by billdenney** [comment]
That’s still 3 significant figures (“1.00”) when it should be 2 (“1.0”).  And the same applies for all values >=1.

**Comment by billdenney** [comment]
@gaborcsardi , Ping on this PR.  Do you have concerns or could it be merged?

**Comment by gaborcsardi** [comment]
I can't recall why I created this, but the original is now merged, so I guess we don't need it.

**Pull request closed without merging**
