### PR TITLE
Optionally skip test requiring 'codetools'

### PR DESCRIPTION
**Pull request by MichaelChirico**
Recommended package is not available on all installations

### CODE REVIEW

**Comment by gaborcsardi** [comment]
As you probably know by now, I am not a big fan of skipping test cases. This package suggests codetools, so it should be there for the tests.

**Comment by MichaelChirico** [comment]
SGTM! I'll close.

(I'll try and keep the mental note this time that it is Gabor that dislikes skips -- I knew it was someone but had forgotten who 🫠)

**Comment by gaborcsardi** [comment]
No worries. If you need these skips in your workflows, then we can have them, with an extra opt in env var, e.g. if you set `SKIP_OPTIONAL_TESTS=true` or something like that?

**Comment by MichaelChirico** [comment]
no need. FWIW this comes up because Suggests are excluded from unit tests by default, but it's as simple as including the package as needed in a [BUILD file](https://bazel.build/concepts/build-files). so it's really an 'us' problem, and using skip() is up to taste.

**Pull request closed without merging**
